### ISSUE TITLE
emoji cheat sheet - Quanyin Tang的博客 | Quanyin Blog

### ISSUE THREAD

**Issue by qytang326** [qytang326/Blog-Comment#8]
http://quanyin.tk/blog/2017/08/20/emoji-cheat-sheet/

**Comment by qytang326** [comment]
:bowtie:

**Comment by Timelordlulu** [comment]
请问这个评论系统是用gitment做的吗？我的blog是fork别人的样式，所以不知道应该把gitment的代码放在哪里？想请教一下你orx
